modLoader="javafml"
loaderVersion="[47,)"
license="GNU"

[[mods]]
modId="mediumcore_fix"
version="1.0.0"
displayName="Mediumcore Fix"
authors="Ringoway"
description='''
Fixes the migration bug in Mediumcore mod where old HEALTH_MODIFIER_TAG data is lost when upgrading to the new BASE_HEALTH_TAG system.
'''

[[dependencies.mediumcore_fix]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mediumcore_fix]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mediumcore_fix]]
    modId="mediumcore"
    mandatory=true
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"
